export type Passage = {
  ref: string;
  theme: string;
};

export const MORNING_PASSAGES: Passage[] = [
  { ref: "Genesis 1:1-13", theme: "Light in the beginning" },
  { ref: "Genesis 1:14-31", theme: "The goodness of creation" },
  { ref: "Genesis 2:4-15", theme: "A garden to keep" },
  { ref: "Genesis 12:1-9", theme: "A call to go" },
  { ref: "Genesis 22:1-14", theme: "The Lord will provide" },
  { ref: "Exodus 3:1-12", theme: "Holy ground" },
  { ref: "Exodus 14:13-22", theme: "Stand still and see" },
  { ref: "Exodus 15:1-13", theme: "The song of Moses" },
  { ref: "Exodus 20:1-17", theme: "Words of life" },
  { ref: "Exodus 33:12-23", theme: "Show me your glory" },
  { ref: "Numbers 6:22-27", theme: "The priestly blessing" },
  { ref: "Deuteronomy 6:4-13", theme: "Love the Lord" },
  { ref: "Deuteronomy 8:1-10", theme: "Remember the Lord" },
  { ref: "Deuteronomy 30:11-20", theme: "Choose life" },
  { ref: "Joshua 1:1-9", theme: "Be strong and courageous" },
  { ref: "Ruth 1:16-22", theme: "Where you go, I will go" },
  { ref: "1 Samuel 3:1-10", theme: "Speak, Lord" },
  { ref: "1 Samuel 16:1-13", theme: "The heart the Lord sees" },
  { ref: "1 Samuel 17:45-50", theme: "The battle is the Lord's" },
  { ref: "2 Samuel 7:18-29", theme: "Who am I, O Lord?" },
  { ref: "1 Kings 19:9-18", theme: "A still small voice" },
  { ref: "2 Chronicles 7:12-16", theme: "If my people pray" },
  { ref: "Nehemiah 8:1-12", theme: "The joy of the Lord" },
  { ref: "Job 38:1-18", theme: "Where were you?" },
  { ref: "Psalm 1", theme: "Planted by streams" },
  { ref: "Psalm 8", theme: "How majestic is your name" },
  { ref: "Psalm 16", theme: "You make known the path of life" },
  { ref: "Psalm 19", theme: "The heavens declare" },
  { ref: "Psalm 23", theme: "The Lord is my shepherd" },
  { ref: "Psalm 24", theme: "The King of glory" },
  { ref: "Psalm 27:1-14", theme: "The Lord is my light" },
  { ref: "Psalm 32", theme: "Blessed is the forgiven" },
  { ref: "Psalm 34:1-18", theme: "Taste and see" },
  { ref: "Psalm 37:1-11", theme: "Trust in the Lord" },
  { ref: "Psalm 40:1-11", theme: "He drew me from the pit" },
  { ref: "Psalm 42", theme: "As the deer pants" },
  { ref: "Psalm 46", theme: "God is our refuge" },
  { ref: "Psalm 51:1-17", theme: "Create in me a clean heart" },
  { ref: "Psalm 63", theme: "My soul thirsts for you" },
  { ref: "Psalm 67", theme: "May God be gracious" },
  { ref: "Psalm 84", theme: "How lovely is your dwelling" },
  { ref: "Psalm 90", theme: "Teach us to number our days" },
  { ref: "Psalm 91", theme: "Under his wings" },
  { ref: "Psalm 95:1-7", theme: "Let us worship" },
  { ref: "Psalm 96", theme: "Sing a new song" },
  { ref: "Psalm 100", theme: "Make a joyful noise" },
  { ref: "Psalm 103", theme: "Bless the Lord, O my soul" },
  { ref: "Psalm 121", theme: "My help comes from the Lord" },
  { ref: "Psalm 130", theme: "Out of the depths" },
  { ref: "Psalm 139:1-18", theme: "You know me" },
  { ref: "Psalm 145:1-21", theme: "Great is the Lord" },
  { ref: "Psalm 150", theme: "Let everything praise" },
  { ref: "Proverbs 3:1-12", theme: "Trust in the Lord" },
  { ref: "Proverbs 4:20-27", theme: "Guard your heart" },
  { ref: "Proverbs 8:1-21", theme: "Wisdom calls" },
  { ref: "Ecclesiastes 3:1-15", theme: "A time for every purpose" },
  { ref: "Isaiah 6:1-8", theme: "Here I am, send me" },
  { ref: "Isaiah 9:2-7", theme: "A child is born" },
  { ref: "Isaiah 26:1-9", theme: "Perfect peace" },
  { ref: "Isaiah 40:1-11", theme: "Comfort my people" },
  { ref: "Isaiah 40:27-31", theme: "Those who wait" },
  { ref: "Isaiah 43:1-7", theme: "I have called you by name" },
  { ref: "Isaiah 53:1-12", theme: "The suffering servant" },
  { ref: "Isaiah 55:1-13", theme: "Come, everyone who thirsts" },
  { ref: "Isaiah 61:1-4", theme: "Good news for the poor" },
  { ref: "Jeremiah 1:4-10", theme: "Before I formed you" },
  { ref: "Jeremiah 17:5-10", theme: "A tree by the water" },
  { ref: "Jeremiah 29:11-14", theme: "Plans for hope" },
  { ref: "Jeremiah 31:31-34", theme: "A new covenant" },
  { ref: "Lamentations 3:19-26", theme: "Great is your faithfulness" },
  { ref: "Ezekiel 36:24-28", theme: "A new heart" },
  { ref: "Ezekiel 37:1-14", theme: "Dry bones live" },
  { ref: "Daniel 3:16-28", theme: "We will not bow" },
  { ref: "Daniel 6:16-23", theme: "The den of lions" },
  { ref: "Hosea 6:1-6", theme: "Let us return" },
  { ref: "Joel 2:12-17", theme: "Rend your hearts" },
  { ref: "Micah 6:6-8", theme: "What the Lord requires" },
  { ref: "Habakkuk 3:17-19", theme: "Yet I will rejoice" },
  { ref: "Zephaniah 3:14-17", theme: "He will rejoice over you" },
  { ref: "Malachi 3:16-18", theme: "Those who feared the Lord" },
  { ref: "Matthew 5:1-16", theme: "The Beatitudes" },
  { ref: "Matthew 5:43-48", theme: "Love your enemies" },
  { ref: "Matthew 6:5-15", theme: "How to pray" },
  { ref: "Matthew 6:25-34", theme: "Do not be anxious" },
  { ref: "Matthew 7:7-14", theme: "Ask, seek, knock" },
  { ref: "Matthew 11:25-30", theme: "Come to me" },
  { ref: "Matthew 13:31-46", theme: "The kingdom is near" },
  { ref: "Matthew 14:22-33", theme: "Take heart, it is I" },
  { ref: "Matthew 16:13-20", theme: "Who do you say I am?" },
  { ref: "Matthew 18:21-35", theme: "Forgive as you are forgiven" },
  { ref: "Matthew 25:31-40", theme: "The least of these" },
  { ref: "Matthew 28:1-10", theme: "He is risen" },
  { ref: "Matthew 28:16-20", theme: "Go and make disciples" },
  { ref: "Mark 1:9-20", theme: "The kingdom is at hand" },
  { ref: "Mark 2:1-12", theme: "Your sins are forgiven" },
  { ref: "Mark 4:35-41", theme: "Peace, be still" },
  { ref: "Mark 5:21-34", theme: "Daughter, your faith has made you well" },
  { ref: "Mark 8:34-38", theme: "Take up your cross" },
  { ref: "Mark 10:13-16", theme: "Let the children come" },
  { ref: "Mark 10:46-52", theme: "I want to see" },
  { ref: "Luke 1:26-38", theme: "Let it be to me" },
  { ref: "Luke 1:46-55", theme: "My soul magnifies the Lord" },
  { ref: "Luke 2:1-20", theme: "Good news of great joy" },
  { ref: "Luke 4:16-21", theme: "The Spirit of the Lord" },
  { ref: "Luke 5:1-11", theme: "Put out into the deep" },
  { ref: "Luke 6:27-36", theme: "Be merciful" },
  { ref: "Luke 10:25-37", theme: "The good Samaritan" },
  { ref: "Luke 11:1-13", theme: "Teach us to pray" },
  { ref: "Luke 12:22-34", theme: "Do not fear, little flock" },
  { ref: "Luke 15:11-24", theme: "The father runs" },
  { ref: "Luke 19:1-10", theme: "Today salvation has come" },
  { ref: "Luke 24:13-35", theme: "The road to Emmaus" },
  { ref: "John 1:1-18", theme: "The Word became flesh" },
  { ref: "John 3:1-17", theme: "Born from above" },
  { ref: "John 4:7-26", theme: "Living water" },
  { ref: "John 6:35-40", theme: "I am the bread of life" },
  { ref: "John 8:12-36", theme: "The light of the world" },
  { ref: "John 10:1-16", theme: "The good shepherd" },
  { ref: "John 11:17-27", theme: "I am the resurrection" },
  { ref: "John 13:1-17", theme: "He washed their feet" },
  { ref: "John 14:1-14", theme: "I am the way" },
  { ref: "John 15:1-17", theme: "Abide in me" },
  { ref: "John 17:1-19", theme: "That they may be one" },
  { ref: "John 20:19-31", theme: "Peace be with you" },
  { ref: "John 21:15-19", theme: "Feed my sheep" },
  { ref: "Acts 1:6-11", theme: "You will be my witnesses" },
  { ref: "Acts 2:1-21", theme: "The day of Pentecost" },
  { ref: "Acts 9:1-19", theme: "A light from heaven" },
  { ref: "Acts 16:25-34", theme: "Believe in the Lord Jesus" },
  { ref: "Romans 5:1-11", theme: "Peace with God" },
  { ref: "Romans 8:1-17", theme: "No condemnation" },
  { ref: "Romans 8:18-39", theme: "More than conquerors" },
  { ref: "Romans 12:1-13", theme: "A living sacrifice" },
  { ref: "1 Corinthians 13:1-13", theme: "The greatest is love" },
  { ref: "1 Corinthians 15:1-11", theme: "Of first importance" },
  { ref: "2 Corinthians 4:6-18", theme: "Treasure in jars of clay" },
  { ref: "2 Corinthians 5:14-21", theme: "A new creation" },
  { ref: "2 Corinthians 12:7-10", theme: "My grace is sufficient" },
  { ref: "Galatians 5:16-26", theme: "The fruit of the Spirit" },
  { ref: "Ephesians 1:3-14", theme: "Blessed in Christ" },
  { ref: "Ephesians 2:1-10", theme: "By grace you have been saved" },
  { ref: "Ephesians 3:14-21", theme: "Rooted in love" },
  { ref: "Ephesians 4:1-16", theme: "Walk worthy" },
  { ref: "Ephesians 6:10-18", theme: "The whole armor of God" },
  { ref: "Philippians 2:1-11", theme: "The mind of Christ" },
  { ref: "Philippians 4:4-13", theme: "Rejoice in the Lord" },
  { ref: "Colossians 1:15-23", theme: "The image of the invisible God" },
  { ref: "Colossians 3:1-17", theme: "Set your mind on things above" },
  { ref: "1 Thessalonians 4:13-18", theme: "The Lord himself will descend" },
  { ref: "1 Thessalonians 5:12-24", theme: "Rejoice always" },
  { ref: "2 Timothy 1:3-14", theme: "Fan into flame" },
  { ref: "Titus 2:11-14", theme: "The grace of God has appeared" },
  { ref: "Hebrews 4:12-16", theme: "The word of God is living" },
  { ref: "Hebrews 11:1-16", theme: "Faith is the assurance" },
  { ref: "Hebrews 12:1-13", theme: "Run with endurance" },
  { ref: "James 1:2-18", theme: "Count it all joy" },
  { ref: "James 1:19-27", theme: "Be doers of the word" },
  { ref: "1 Peter 1:3-9", theme: "A living hope" },
  { ref: "1 Peter 2:4-10", theme: "A chosen people" },
  { ref: "1 Peter 5:6-11", theme: "Cast your cares" },
  { ref: "1 John 1:1-10", theme: "Walk in the light" },
  { ref: "1 John 4:7-21", theme: "God is love" },
  { ref: "Revelation 1:12-18", theme: "I am the first and the last" },
  { ref: "Revelation 7:9-17", theme: "A multitude no one could number" },
  { ref: "Revelation 21:1-7", theme: "A new heaven and a new earth" },
  { ref: "Revelation 22:1-7", theme: "The river of life" },
  { ref: "Psalm 119:1-16", theme: "Blessed are those who walk" },
  { ref: "Psalm 119:97-112", theme: "Your word is a lamp" },
  { ref: "Proverbs 31:10-31", theme: "Strength and dignity" },
  { ref: "Isaiah 58:6-12", theme: "The fast the Lord chooses" },
  { ref: "Matthew 5:17-24", theme: "Reconcile with your brother" },
  { ref: "Luke 6:37-45", theme: "A good tree bears good fruit" },
  { ref: "John 3:16-21", theme: "God so loved the world" },
  { ref: "Acts 4:23-31", theme: "They spoke the word with boldness" },
  { ref: "Romans 15:1-13", theme: "The God of hope" },
  { ref: "2 Timothy 3:14-17", theme: "All Scripture is breathed out" }
];
